### ISSUE TITLE
cannot set pin interrupt

### ISSUE THREAD

**Issue by kaseymccurdy** [Frijol/PIR#12]
Just curious if you've run into this issue...it started happening suddenly:

```
/usr/lib/node/tessel-export.js:566
        throw new Error('Cannot set pin interrupt mode to ' + mode +
        ^

Error: Cannot set pin interrupt mode to fall; already listening for rise
    at Tessel.pwmFrequency.Tessel.Pin.addListener (/usr/lib/node/tessel-export.js:566:15)
    at e (/tmp/remote-script/node_modules/pir/index.js:1:326)
    at Function.use (/tmp/remote-script/node_modules/pir/index.js:1:634)
    at Object.<anonymous> (/tmp/remote-script/index.js:1:139)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
```

Thanks!

**Comment by kaseymccurdy** [comment]
I'll just leave this here as a comment in case anyone else . If you flash the Tessel...make sure you run `t2 update` to get the latest firmware and software for the Tessel. Otherwise, you'll spend too much time digging into source code and low-level hardware specifics when really all you had was `code incompatible with the old version you were running.` 🤦🏼‍♂️
