### ISSUE TITLE
Can't get T2 work with PIR

### ISSUE THREAD

**Issue by peterschmiz** [Frijol/PIR#9]
Hi,

I got the following error after installing pir (npm install pir) and try to run the example:

`Error: Specified pin is not a digital pin: 2
    at Error (native)
    at new e (/tmp/remote-script/node_modules/pir/index.js:1:281)
    at Object.r [as use] (/tmp/remote-script/node_modules/pir/index.js:1:668)
    at Object.<anonymous> (/tmp/remote-script/pir.js:1:104)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)`

Is the npm package updated to support T2?

**Comment by Frijol** [comment]
As of version 0.2.0, should work! Please let me know if it does not.
